import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#000000',
    },
    loadingText: {
        color: '#fff',
        marginTop: 12,
        fontSize: 16,
    },
    errorContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 16,
        backgroundColor: '#000000',
    },
    errorText: {
        textAlign: 'center',
        fontSize: 18,
        color: '#ef4444',
    },
    container: {
        flex: 1,
        backgroundColor: '#000000',
    },
    bannerContainer: {
        height: 256,
        width: '100%',
    },
    banner: {
        width: '100%',
        height: '100%',
    },
    bannerPlaceholder: {
        width: '100%',
        height: '100%',
        backgroundColor: '#3b82f6',
        justifyContent: 'center',
        alignItems: 'center',
    },
    bannerPlaceholderText: {
        color: '#ffffff',
        fontSize: 24,
        fontWeight: 'bold',
    },
    avatarContainer: {
        position: 'absolute',
        top: 208,
        left: 24,
    },
    avatar: {
        width: 96,
        height: 96,
        borderRadius: 48,
        borderWidth: 4,
        borderColor: '#ffffff',
    },
    avatarPlaceholder: {
        width: 96,
        height: 96,
        borderRadius: 48,
        borderWidth: 4,
        borderColor: '#ffffff',
        backgroundColor: '#e5e7eb',
        justifyContent: 'center',
        alignItems: 'center',
    },
    avatarPlaceholderText: {
        fontSize: 30,
        fontWeight: 'bold',
        color: '#4b5563',
    },
    content: {
        marginTop: 80,
        paddingHorizontal: 24,
    },
    titleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#ffffff',
        marginRight: 8,
    },
    description: {
        color: '#d1d5db',
        fontSize: 15,
        lineHeight: 22,
    },
    tagsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 16,
    },
    tag: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 16,
        backgroundColor: '#1e3a8a',
        marginRight: 8,
        marginBottom: 8,
    },
    tagText: {
        marginLeft: 4,
        fontSize: 14,
        color: '#bfdbfe',
    },
    ownerBadge: {
        backgroundColor: '#7c3aed',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 8,
        marginVertical: 16,
        alignItems: 'center',
    },
    ownerText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    actionsContainer: {
        flexDirection: 'column',
        marginTop: 24,
        gap: 12,
    },
    ownerActionsContainer: {
        flexDirection: 'row',
        gap: 12,
        width: '100%',
    },
    joinButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        backgroundColor: '#3b82f6',
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 8,
        width: '100%',
    },
    leaveButton: {
        backgroundColor: '#6b7280',
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 8,
        width: '100%',
        alignItems: 'center',
    },
    editButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        backgroundColor: '#7c3aed',
        paddingVertical: 12,
        borderRadius: 8,
    },
    deleteButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        backgroundColor: '#ef4444',
        paddingVertical: 12,
        borderRadius: 8,
    },
    shareButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        backgroundColor: 'transparent',
        borderWidth: 2,
        borderColor: '#7c3aed',
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 8,
        marginTop: 8,
    },
    buttonText: {
        color: '#ffffff',
        fontWeight: '600',
        fontSize: 15,
    },
    shareButtonText: {
        color: '#7c3aed',
        fontWeight: '600',
        fontSize: 15,
    },
    infoSection: {
        marginTop: 32,
        borderTopWidth: 1,
        borderTopColor: '#374151',
        paddingTop: 16,
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    infoText: {
        marginLeft: 8,
        color: '#9ca3af',
        fontSize: 15,
    },
    creatorAvatar: {
        width: 64,
        height: 64,
        backgroundColor: '#e5e7eb',
        borderWidth: 2,
        borderStyle: 'dashed',
        borderRadius: 12,
    },
    creatorInfo: {
        marginLeft: 12,
    },
    creatorLabel: {
        fontSize: 14,
        color: '#6b7280',
    },
    creatorName: {
        fontWeight: '500',
        color: '#ffffff',
    },
    navigation: {
        marginTop: 48,
    },
    navigationTabs: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        borderBottomWidth: 1,
        borderBottomColor: '#374151',
        paddingVertical: 8,
    },
    navigationActive: {
        color: '#2563eb',
        fontWeight: '500',
    },
    navigationInactive: {
        color: '#9ca3af',
    },
});