services:
  # Servicio del frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: next-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules   # preserva dependencias
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: "dpu6bvxkc"
      NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET: "default"
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: 300
      WATCHPACK_POLLING: "true"
    networks:
      - app-network

  # Servicio de la base de datos (PostgreSQL)
  postgres:
    image: postgres:14-alpine
    container_name: nest-db
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "knoword"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Servicio de la caché (Redis)
  redis:
    image: redis:6-alpine
    container_name: nest-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # Servicio de migraciones (solo se ejecuta y se apaga)
  migration:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules   # preserva dependencias para evitar errores
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/knoword"
    command: npx prisma migrate dev --name init
    networks:
      - app-network

  # Servicio del backend (Nest.js)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nest-backend
    command: sh -c "npx prisma generate && npm run start:dev"
    volumes:
      - ./backend:/app
      - /app/node_modules   # preserva dependencias
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/knoword"
      JWT_SECRET: "supersecretkey"
      JWT_ACCESS_SECRET: "ultrasecret"
      JWT_REFRESH_SECRET: "ultrasecret"
      MAIL_HOST: "sandbox.smtp.mailtrap.io"
      MAIL_PORT: "2525"
      MAIL_USER: "89e2e562a677c7"
      MAIL_PASSWORD: "1863913a748514"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      PORT: 8000
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: 300
      WATCHPACK_POLLING: "true"
      TS_NODE_TRANSPILE_ONLY: "true"
    depends_on:
      - postgres
      - redis
      - migration
    networks:
      - app-network

  # Servicio para Prisma Studio
  prisma-studio:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nest-prisma-studio
    command: npx prisma studio
    volumes:
      - ./backend:/app
      - /app/node_modules   # preserva dependencias
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/knoword"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
