import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#000",
        paddingHorizontal: 16,
        paddingTop: 24,
    },
    title: {
        color: "#fff",
        fontSize: 24,
        fontWeight: "bold",
        marginBottom: 24,
        textTransform: "capitalize",
    },
    loadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#000",
    },
    spinner: {
        width: 48,
        height: 48,
        borderTopWidth: 2,
        borderBottomWidth: 2,
        borderColor: "#3b82f6",
        borderRadius: 24,
    },
    card: {
        backgroundColor: "#1f1f1f",
        borderRadius: 16,
        marginBottom: 24,
        overflow: "hidden",
    },
    banner: {
        height: 96,
        position: "relative",
    },
    bannerImage: {
        width: "100%",
        height: "100%",
    },
    bannerFallback: {
        width: "100%",
        height: "100%",
        backgroundColor: "#3b82f6",
    },
    avatarContainer: {
        position: "absolute",
        bottom: -24,
        left: 16,
    },
    avatarImage: {
        width: 48,
        height: 48,
        borderRadius: 24,
        borderWidth: 2,
        borderColor: "#121212",
    },
    avatarFallback: {
        width: 48,
        height: 48,
        borderRadius: 24,
        borderWidth: 2,
        borderColor: "#121212",
        backgroundColor: "#4b5563",
        justifyContent: "center",
        alignItems: "center",
    },
    avatarFallbackText: {
        color: "#fff",
        fontWeight: "bold",
        fontSize: 18,
    },
    privacyBadge: {
        position: "absolute",
        top: 8,
        right: 8,
        backgroundColor: "#facc15",
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 999,
    },
    privacyText: {
        color: "#78350f",
        fontSize: 10,
        fontWeight: "500",
    },
    content: {
        paddingTop: 32,
        paddingBottom: 16,
        paddingHorizontal: 16,
    },
    communityName: {
        color: "#fff",
        fontSize: 18,
        fontWeight: "bold",
        marginBottom: 4,
    },
    description: {
        color: "#9ca3af",
        fontSize: 14,
        marginBottom: 12,
    },
    tagsContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 4,
        marginBottom: 12,
    },
    tag: {
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 999,
        backgroundColor: "#1e3a8a",
    },
    tagText: {
        color: "#bfdbfe",
        fontSize: 12,
        fontWeight: "500",
    },
    tagOverflow: {
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 999,
        backgroundColor: "#374151",
    },
    tagOverflowText: {
        color: "#d1d5db",
        fontSize: 12,
        fontWeight: "500",
    },
    footer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    footerText: {
        color: "#9ca3af",
        fontSize: 12,
    },
    empty: {
        color: "#9CA3AF",
        textAlign: "center",
        marginTop: 24,
        fontSize: 14,
    },

    joinButton: {
        marginTop: 8,
        backgroundColor: "#3B82F6",
        paddingVertical: 8,
        borderRadius: 6,
        alignItems: "center",
    },
    joinButtonText: {
        color: "#fff",
        fontWeight: "600",
        fontSize: 14,
    },
    detailButton: {
        marginTop: 6,
        backgroundColor: "#374151",
        paddingVertical: 8,
        borderRadius: 6,
        alignItems: "center",
    },
    detailButtonText: {
        color: "#fff",
        fontWeight: "500",
        fontSize: 13,
    },
});