import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 120,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#ffffff',
  },
  section: {
    backgroundColor: '#111827',
    borderRadius: 12,
    padding: 20,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: 6,
  },
  sectionDescription: {
    fontSize: 13,
    color: '#9ca3af',
    marginBottom: 20,
    lineHeight: 18,
  },
  fieldContainer: {
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
    color: '#ffffff',
  },
  input: {
    width: '100%',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: '#1f2937',
    color: '#ffffff',
    borderWidth: 1,
    borderColor: '#374151',
    fontSize: 15,
  },
  textArea: {
    minHeight: 100,
    textAlignVertical: 'top',
  },
  inputError: {
    borderColor: '#ef4444',
  },
  errorText: {
    color: '#f87171',
    fontSize: 13,
    marginTop: 6,
  },
  privacyContainer: {
    marginTop: 4,
  },
  privacyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  toggle: {
    height: 28,
    width: 50,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 2,
  },
  toggleActive: {
    backgroundColor: '#7c3aed',
  },
  toggleInactive: {
    backgroundColor: '#374151',
  },
  toggleThumb: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#ffffff',
  },
  toggleThumbActive: {
    marginLeft: 'auto',
  },
  privacyInfo: {
    marginTop: 4,
  },
  privacyTextPrivate: {
    fontSize: 13,
    color: '#fca5a5',
  },
  privacyTextPublic: {
    fontSize: 13,
    color: '#9ca3af',
  },
  tagsInputWrapper: {
    marginBottom: 12,
  },
  tagCount: {
    fontSize: 12,
    color: '#9ca3af',
    marginTop: 8,
  },
  searchingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    paddingVertical: 8,
  },
  searchingText: {
    fontSize: 13,
    color: '#9ca3af',
    marginLeft: 8,
  },
  suggestionsContainer: {
    marginBottom: 16,
  },
  suggestionsTitle: {
    fontSize: 12,
    color: '#9ca3af',
    marginBottom: 8,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  suggestionsWrapper: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  suggestion: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: '#374151',
    borderRadius: 20,
    marginRight: 8,
    marginBottom: 8,
  },
  suggestionText: {
    color: '#f3f4f6',
    fontSize: 13,
    fontWeight: '500',
  },
  selectedTagsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 12,
  },
  selectedTag: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#7c3aed",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
    marginBottom: 8,
  },
  selectedTagText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "600",
  },
  removeTag: {
    marginLeft: 8,
    paddingHorizontal: 4,
    color: "#ffffff",
    fontSize: 16,
    fontWeight: 'bold',
  },
  bannerUpload: {
    width: '100%',
    height: 140,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#374151',
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1f2937',
    overflow: 'hidden',
  },
  uploadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    zIndex: 10,
  },
  uploadingText: {
    color: '#ffffff',
    marginTop: 8,
    fontSize: 14,
  },
  bannerImage: {
    width: '100%',
    height: '100%',
  },
  uploadPlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadPlaceholderText: {
    color: '#9ca3af',
    fontSize: 13,
    marginTop: 8,
  },
  avatarUploadContainer: {
    alignItems: 'center',
  },
  avatarBox: {
    width: 120,
    height: 120,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#374151',
    borderRadius: 60,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1f2937',
    overflow: 'hidden',
    position: 'relative',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  avatarPlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarUploadText: {
    color: '#9ca3af',
    fontSize: 13,
    marginTop: 12,
  },
  submitButton: {
    paddingVertical: 16,
    backgroundColor: "#7c3aed",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  submitButtonDisabled: {
    backgroundColor: "#4c1d95",
    opacity: 0.6,
  },
  submitButtonText: {
    color: "#ffffff",
    fontWeight: "bold",
    fontSize: 17,
  },
  validationInfo: {
    backgroundColor: '#1f2937',
    padding: 16,
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#ef4444',
    marginBottom: 20,
  },
  validationText: {
    color: '#fca5a5',
    fontSize: 13,
    marginBottom: 4,
  },
});